package com.group6.hms.framework.screens.terminal.mac;// Generated by jextract

import java.lang.foreign.*;

/**
 * {@snippet lang=c :
 * struct termios {
 *     tcflag_t c_iflag;
 *     tcflag_t c_oflag;
 *     tcflag_t c_cflag;
 *     tcflag_t c_lflag;
 *     cc_t c_cc[20];
 *     speed_t c_ispeed;
 *     speed_t c_ospeed;
 * }
 * }
 */
public class termios {

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        termios_h.C_LONG.withName("c_iflag"),
        termios_h.C_LONG.withName("c_oflag"),
        termios_h.C_LONG.withName("c_cflag"),
        termios_h.C_LONG.withName("c_lflag"),
        MemoryLayout.sequenceLayout(20, termios_h.C_CHAR).withName("c_cc"),
        MemoryLayout.paddingLayout(4),
        termios_h.C_LONG.withName("c_ispeed"),
        termios_h.C_LONG.withName("c_ospeed")
    ).withName("termios");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

}

